-- Numéro de réservation lisible (les UUID ne sont pas utilisables comme référence
-- humaine — ex: pour nommer un PDF de contrat "Contrat IVJ #142 - nom client").
alter table public.reservations
  add column numero integer generated by default as identity;

alter table public.reservations
  add constraint reservations_numero_unique unique (numero);
